name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: linz/action-typescript@v1

      - name: Generate JSON
        run: yarn run generate

      - name: Validate Generated
        run: git diff --exit-code

      - name: Publish to NPM
        if: startsWith(github.ref, 'refs/tags/v')
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN_LINZJS}}
